# -*- coding: utf-8 -*-
"""Trabalho Prático 1 de Aprendizado de Máquina - Mateus Filipe valentim - Felipe Kitamoto Amaral

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzqHDF-NZ69kwZJ9Mujf-ruNy7HoZw_j

Bibliotecas Utilizadas
"""

!pip install pandas numpy openpyxl scikit-learn plotly matplotlib seaborn

import pandas as pd
import numpy as np
import os
import openpyxl
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler, OrdinalEncoder, OneHotEncoder, RobustScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV, GridSearchCV, cross_validate, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from IPython.display import display
from scipy.stats import chi2_contingency
from sklearn.model_selection import GroupShuffleSplit
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import classification_report
from sklearn.model_selection import GroupKFold
from sklearn.metrics import confusion_matrix

"""Tratamento de Dados"""

try:
    tabela = pd.read_csv("clientes.csv", encoding="latin")
    display(tabela.head())
    print("\nInformações Iniciais da Tabela:")
    tabela.info()
    print("\nEstatísticas Descritivas:")
    display(tabela.describe())
except FileNotFoundError:
    print("Erro: Arquivo 'clientes.csv' não encontrado.")
    exit()
except Exception as e:
    print(f"Erro ao ler o arquivo: {e}")
    exit()

tabela = tabela.dropna(how='all', axis=1)
tabela = tabela.loc[:, ~tabela.T.duplicated()]
tabela = tabela.drop_duplicates()

tabela[tabela.select_dtypes(include=['int', 'float']).columns] = tabela.select_dtypes(include=['int', 'float']).astype(float)
tabela[['id_cliente', 'mes']] = tabela[['id_cliente', 'mes']].astype(int)

colunas_numericas = tabela.select_dtypes(include=['number']).columns
colunas_categoricas = tabela.select_dtypes(exclude=['number']).columns

tabela_agg = tabela.groupby("id_cliente").agg({
    **{col: "mean" for col in colunas_numericas if col not in ["id_cliente","mes"]},
    **{col: "last" for col in colunas_categoricas if col not in ["id_cliente", "mes"]}
}).reset_index()

display(tabela_agg.head(3))

tabela_agg.to_csv("clientes_agrupado_excel.csv", sep=";", index=False, decimal=".")
tabela_agg.to_csv("clientes_agrupado_libre.csv", sep=';', index=False, decimal=',', encoding='utf-8-sig')

tabela_agg.info()

"""Histogramas e Correlações"""

print("\n--- Distribuição das Variáveis de Clientes por Faixa de Score de Crédito (Histogramas) ---")

for coluna in tabela.columns:

  if coluna in ["id_cliente", "score_credito", "mes"]:
    continue

  histograma = px.histogram(tabela, x=coluna, color="score_credito", barmode="relative", title=f"Distribuição de {coluna} por Score de Crédito", labels={coluna: coluna, "count": ""}, color_discrete_map={"Good": "#636efa", "Standard": "#00cc96", "Poor": "#ef553b"})
  histograma.update_yaxes(title_text="Frequência")

  histograma.show()

print("\n--- Análise de Dispersão das Variáveis Numéricas por Score de Crédito (Boxplots) ---")

for coluna in tabela_agg.columns:

  if coluna in ["id_cliente", "score_credito"]:
    continue

  if pd.api.types.is_numeric_dtype(tabela_agg[coluna]):
    box = px.box(tabela_agg, x="score_credito", y=coluna, points="all", title=f"Distribuição de {coluna} por Score de Crédito")
    box.show()

tabela_transformada = tabela.copy()
tabela_transformada["score_credito_num"] = tabela_transformada["score_credito"].astype(str).map({"Poor": 0, "Standard": 1, "Good": 2})

colunas_numericas_transformadas = tabela_transformada.select_dtypes(include=['number']).columns.drop(["id_cliente", "mes"], errors="ignore")
correlacao = tabela_transformada[colunas_numericas_transformadas].corrwith(tabela_transformada["score_credito_num"]).sort_values(ascending=False)

plt.figure(figsize=(10,5))
sns.barplot(x=correlacao, y=correlacao.index, hue=correlacao.index, legend=False)
plt.title("Correlação das Variáveis Numéricas com Score de Crédito")
plt.xlabel("Coeficiente de Correlação (Pearson)")
plt.ylabel("Variáveis do Cliente")
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

colunas_categoricas_transformadas = tabela_transformada.select_dtypes(include='object').columns.drop('score_credito', errors='ignore')
resultados_correlacao_cramer = []

for coluna in colunas_categoricas_transformadas:
    tabela_contingencia = pd.crosstab(tabela_transformada[coluna], tabela_transformada['score_credito'])
    chi2_stat = chi2_contingency(tabela_contingencia)[0]
    total = tabela_contingencia.sum().sum()
    cramers_valor = np.sqrt(chi2_stat / (total * (min(tabela_contingencia.shape)-1)))
    resultados_correlacao_cramer.append((coluna, cramers_valor))

cramers_df = pd.DataFrame(resultados_correlacao_cramer, columns=['Variáveis do Cliente', 'Força da Associação']).sort_values(by='Força da Associação', ascending=False)

plt.figure(figsize=(10,5))
sns.barplot(x='Força da Associação', y='Variáveis do Cliente', data=cramers_df, hue='Variáveis do Cliente', legend=False)
plt.title("Associação entre Variáveis Categóricas e Score de Crédito (Cramér's V)")
plt.xlabel("Força da Associação (0 = Fraca, 1 = Forte)")
plt.ylabel("Variáveis do Cliente")
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""Separação de Treino e Teste e Transformação/Normalização de features"""

tabela_transformada = tabela.copy()
tabela_transformada["score_credito_num"] = tabela_transformada["score_credito"].astype(str).map({"Poor": 0, "Standard": 1, "Good": 2})
#tabela_transformada = tabela_transformada.drop(columns=["emprestimo_estudantil", "emprestimo_carro", "emprestimo_casa", "emprestimo_pessoal", "emprestimo_credito", "emprestimo_carro", "taxa_uso_credito"])
tabela_transformada[["comportamento_gasto", "comportamento_pagamento"]] = tabela_transformada["comportamento_pagamento"].str.extract(r"(baixo|alto)_gasto_pagamento_(baixo|medio|alto|baixos)")
tabela_transformada["comportamento_pagamento"] = tabela_transformada["comportamento_pagamento"].replace({"baixos": "baixo"})

colunas_ordinais = ["comportamento_pagamento", "comportamento_gasto", "mix_credito"]
categorias_ordinais = [
    ["baixo", "medio", "alto"],
    ["baixo", "alto"],
    ["Ruim", "Normal", "Bom"]
]

coluna_onehot = ["profissao"]

colunas_numericas = [col for col in tabela_transformada.select_dtypes(include=['number']).columns
                if col not in ["id_cliente", "mes", "score_credito_num"]]

colunas = tabela_transformada.drop(columns=["score_credito_num", "score_credito"])
rotulos = tabela_transformada["score_credito_num"]

colunas_treino, colunas_teste, rotulos_treino, rotulos_teste = train_test_split(
    colunas, rotulos, test_size=0.2, random_state=42, stratify=rotulos
)

colunas_treino = colunas_treino.drop(columns=["id_cliente"])
colunas_teste = colunas_teste.drop(columns=["id_cliente"])

print(f"Tamanho do treino: {colunas_treino.shape}")
print(f"Tamanho do teste: {colunas_teste.shape}")

preprocessamento = ColumnTransformer(
    transformers=[
        ("nominal", OneHotEncoder(sparse_output=False, handle_unknown="ignore"), coluna_onehot),
        ("ordinal", OrdinalEncoder(categories=categorias_ordinais, dtype=float), colunas_ordinais),
        ("numerico", RobustScaler(), colunas_numericas)
    ],
    remainder="passthrough"
)

"""Pipelines"""

pipeline_random_forest = Pipeline(steps=[
    ('preprocessor', preprocessamento),
    ('classifier', RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    bootstrap=True,
    class_weight='balanced',
    random_state=42
)
)
])

pipeline_knn = Pipeline(steps=[
    ('preprocessor', preprocessamento),
    ('classifier', KNeighborsClassifier(
    n_neighbors=9,
    weights='distance',
    metric='minkowski',
    p=2
))
])

pipeline_arvore_decisao = Pipeline(steps=[
    ('preprocessor', preprocessamento),
    ('classifier', DecisionTreeClassifier(
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    criterion='gini',
    class_weight='balanced',
    random_state=42
))
])

"""Teste de Modelos com Train Test Split aleatorio 80/20"""

pipeline_random_forest.fit(colunas_treino, rotulos_treino)
pipeline_knn.fit(colunas_treino, rotulos_treino)
pipeline_arvore_decisao.fit(colunas_treino, rotulos_treino)

predicao_random_forest = pipeline_random_forest.predict(colunas_teste)
predicao_knn = pipeline_knn.predict(colunas_teste)
predicao_arvore_decisao = pipeline_arvore_decisao.predict(colunas_teste)

def definir_metricas(rotulo_real, rotulo_predito):
  print(f"Acurácia: {accuracy_score(rotulo_real, rotulo_predito):.4f}")
  print(f"Precisão: {precision_score(rotulo_real, rotulo_predito, average='weighted'):.4f}")
  print(f"Recall: {recall_score(rotulo_real, rotulo_predito, average='weighted'):.4f}")
  print(f"F1-score: {f1_score(rotulo_real, rotulo_predito, average='weighted'):.4f}")
  return {
                'accuracia': accuracy_score(rotulo_real, rotulo_predito),
                'precisao': precision_score(rotulo_real, rotulo_predito, average='weighted'),
                'recall': recall_score(rotulo_real, rotulo_predito, average='weighted'),
                'f1': f1_score(rotulo_real, rotulo_predito, average='weighted')
          }

def grafico_metricas_modelos(tabela_metricas):

    if tabela_metricas.index.name is None:
        tabela_metricas.index.name = "Modelo"

    tabela_metrica_melt = tabela_metricas.reset_index().melt(
        id_vars="Modelo",
        var_name="Métrica",
        value_name="Valor"
    )

    grafico_metricas = px.bar(
        tabela_metrica_melt,
        x="Modelo",
        y="Valor",
        color="Métrica",
        barmode="group",
        text="Valor",
        title="Comparação de Métricas entre Modelos",
        labels={"Valor": "Valor da Métrica", "Modelo": "Modelo", "Métrica": "Tipo de Métrica"}
    )

    grafico_metricas.update_traces(texttemplate="%{text:.2f}", textposition="outside")
    grafico_metricas.update_layout(
        yaxis_range=[0, 1],
        title_x=0.5,
        legend_title_text="Métricas",
        uniformtext_minsize=8,
        uniformtext_mode="hide",
        bargap=0.15
    )

    grafico_metricas.show()

print("===== Métricas dos Modelos =====")
print()
print("Random Forest: ")
metricas_random_forest = definir_metricas(rotulos_teste, predicao_random_forest)
print()
print("KNN: ")
metricas_knn = definir_metricas(rotulos_teste, predicao_knn)
print()
print("Árvore de Decisão: ")
metricas_arvore_decisao = definir_metricas(rotulos_teste, predicao_arvore_decisao)

tabela_metricas = pd.DataFrame({
    'Random Forest': metricas_random_forest,
    'KNN': metricas_knn,
    'Árvore de Decisão': metricas_arvore_decisao
}).T

grafico_metricas_modelos(tabela_metricas)

"""Treino de Modelos usando Cros Validaiton"""

print("===== Métricas dos Modelos com Cross Validation =====")
print()

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
metricas_cv = ['accuracy', 'precision_weighted', 'recall_weighted', 'f1_weighted']

metricas_random_forest_cv = cross_validate(pipeline_random_forest, colunas, rotulos, cv=cv, scoring=metricas_cv, groups = tabela_transformada["id_cliente"])
print("Random Forest")
print(f"RF - Accuracy: {metricas_random_forest_cv['test_accuracy'].mean():.4f} ± {metricas_random_forest_cv['test_accuracy'].std():.4f}")
print(f"RF - Precision: {metricas_random_forest_cv['test_precision_weighted'].mean():.4f} ± {metricas_random_forest_cv['test_precision_weighted'].std():.4f}")
print(f"RF - Recall: {metricas_random_forest_cv['test_recall_weighted'].mean():.4f} ± {metricas_random_forest_cv['test_recall_weighted'].std():.4f}")
print(f"RF - F1-score: {metricas_random_forest_cv['test_f1_weighted'].mean():.4f} ± {metricas_random_forest_cv['test_f1_weighted'].std():.4f}")
print()

metricas_knn_cv = cross_validate(pipeline_knn, colunas, rotulos, cv=cv, scoring=metricas_cv, groups = tabela_transformada["id_cliente"])
print("K-Nearest Neighbors")
print(f"KNN - Accuracy: {metricas_knn_cv['test_accuracy'].mean():.4f} ± {metricas_knn_cv['test_accuracy'].std():.4f}")
print(f"KNN - Precision: {metricas_knn_cv['test_precision_weighted'].mean():.4f} ± {metricas_knn_cv['test_precision_weighted'].std():.4f}")
print(f"KNN - Recall: {metricas_knn_cv['test_recall_weighted'].mean():.4f} ± {metricas_knn_cv['test_recall_weighted'].std():.4f}")
print(f"KNN - F1-score: {metricas_knn_cv['test_f1_weighted'].mean():.4f} ± {metricas_knn_cv['test_f1_weighted'].std():.4f}")
print()


metricas_arvore_decisao_cv = cross_validate(pipeline_arvore_decisao, colunas, rotulos, cv=cv, scoring=metricas_cv, groups = tabela_transformada["id_cliente"])
print("Árvore De Decisão")
print(f"AD - Accuracy: {metricas_arvore_decisao_cv['test_accuracy'].mean():.4f} ± {metricas_arvore_decisao_cv['test_accuracy'].std():.4f}")
print(f"AD - Precision: {metricas_arvore_decisao_cv['test_precision_weighted'].mean():.4f} ± {metricas_arvore_decisao_cv['test_precision_weighted'].std():.4f}")
print(f"AD - Recall: {metricas_arvore_decisao_cv['test_recall_weighted'].mean():.4f} ± {metricas_arvore_decisao_cv['test_recall_weighted'].std():.4f}")
print(f"AD - F1-score: {metricas_arvore_decisao_cv['test_f1_weighted'].mean():.4f} ± {metricas_arvore_decisao_cv['test_f1_weighted'].std():.4f}")
print()

tabela_metricas_cv = pd.DataFrame({
    "Random Forest": {
        "Acurácia": metricas_random_forest_cv['test_accuracy'].mean(),
        "Precisão": metricas_random_forest_cv['test_precision_weighted'].mean(),
        "Recall": metricas_random_forest_cv['test_recall_weighted'].mean(),
        "F1": metricas_random_forest_cv['test_f1_weighted'].mean()
    },
    "KNN": {
        "Acurácia": metricas_knn_cv['test_accuracy'].mean(),
        "Precisão": metricas_knn_cv['test_precision_weighted'].mean(),
        "Recall": metricas_knn_cv['test_recall_weighted'].mean(),
        "F1": metricas_knn_cv['test_f1_weighted'].mean()
    },
    "Árvore de Decisão": {
        "Acurácia": metricas_arvore_decisao_cv['test_accuracy'].mean(),
        "Precisão": metricas_arvore_decisao_cv['test_precision_weighted'].mean(),
        "Recall": metricas_arvore_decisao_cv['test_recall_weighted'].mean(),
        "F1": metricas_arvore_decisao_cv['test_f1_weighted'].mean()
    }
}).T

grafico_metricas_modelos(tabela_metricas_cv)

"""Treino de modelos por meio do Grid Search"""

def grid_search(
    pipelines,
    param_grids,
    colunas_treino,
    rotulos_treino,
    colunas_reais,
    rotulos_reais,
    cv_splits=2
):

    resultados = {}
    cv = StratifiedKFold(n_splits=cv_splits, shuffle=True, random_state=42)

    for nome, pipeline in pipelines.items():
        print(f"\n=== GridSearchCV para {nome} ===")
        param_grid = param_grids[nome]

        grid_resultados = GridSearchCV(
            estimator=pipeline,
            param_grid=param_grid,
            cv=cv,
            scoring='accuracy',
            n_jobs=1,
            verbose=3
        )
        grid_resultados.fit(colunas_treino, rotulos_treino)
        melhor_modelo = grid_resultados.best_estimator_
        rotulos_predito = melhor_modelo.predict(colunas_reais)

        print(f"\nMelhores parâmetros para {nome}: {grid_resultados.best_params_}")
        metricas = definir_metricas(rotulos_reais, rotulos_predito)

        resultados[nome] = {
            'modelo': melhor_modelo,
            'best_params': grid_resultados.best_params_,
            'metrics':  metricas
        }

    return resultados

pipelines = {
    'KNN': pipeline_knn,
    'Decision Tree': pipeline_arvore_decisao,
    'Random Forest': pipeline_random_forest,

}

param_grids = {
    'Random Forest': {
        'classifier__n_estimators': [500, 700],
        'classifier__max_depth': [15, None],
        'classifier__min_samples_split': [2, 5],
        'classifier__min_samples_leaf': [2, 4],
        'classifier__max_features': ['log2','sqrt'],
        'classifier__class_weight': ['balanced'],
        'classifier__bootstrap' : [True],
        'classifier__random_state': [42]
    },
    'KNN': {
        'classifier__n_neighbors': [7, 9, 11],
        'classifier__weights': ['uniform','distance'],
        'classifier__p': [2],
        'classifier__metric': ['minkowski','manhattan'],
    },
'Decision Tree': {
    'classifier__criterion': ['gini', 'entropy', 'log_loss'],
    'classifier__max_depth': [None, 20, 15],
    'classifier__min_samples_split': [2, 5, 20],
    'classifier__min_samples_leaf': [2, 4, 8],
    'classifier__max_features': [ 'sqrt', 'log2'],
    'classifier__class_weight': [ 'balanced'],
    'classifier__splitter': ['best', 'random'],
    'classifier__random_state': [42]
}
}

print("===== Métricas dos Modelos com Grid Search =====")

resultados = grid_search(
    pipelines, param_grids, colunas_treino, rotulos_treino, colunas_teste, rotulos_teste
)

tabela_metricas_grid = pd.DataFrame({
    nome: resultado['metrics']
    for nome, resultado in resultados.items()
}).T
grafico_metricas_modelos(tabela_metricas_grid)

"""Matriz de Confusão"""

classes = ['Poor', 'Standard', 'Good']

def plot_matriz_confusao(resultados, rotulos_reais):
    for nome, info in resultados.items():
        modelo = info['modelo']
        rotulos_predito = modelo.predict(colunas_teste)
        cm = confusion_matrix(rotulos_reais, rotulos_predito, labels=[0,1,2])
        plt.figure(figsize=(6,5))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False, xticklabels=classes, yticklabels=classes)
        plt.title(f'Matriz de Confusão - {nome}')
        plt.xlabel('Predito')
        plt.ylabel('Real')
        plt.show()

plot_matriz_confusao(resultados, rotulos_reais=rotulos_teste)